#spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 10
#    jedis:
#      pool:
#        max-wait: 1
#        max-idle: 8
#        min-idle: 0
#    database: 0
#    password:
#
##日志
## 方式一  引入文件
##logging:
##  config: classpath:log4j2.xml
#
## 方式二
#logging:
#  path: /data/applogs/ytDemo
#
#
#jdbc:
#    name: test
#    url: jdbc:mysql://127.0.0.1:3306/yt_demo
#    username: root
#    password: 123456
#    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20


