server:
  port: 8090
  servlet:
    context-path: /yyt

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10
    jedis:
      pool:
        max-wait: 1
        max-idle: 8
        min-idle: 0
    database: 0
    password:

#日志
# 方式一  引入文件
#logging:
#  config: classpath:log4j2.xml

# 方式二
logging:
  path: /data/applogs/ytDemo


jdbc:
  name: test
  url: jdbc:mysql://127.0.0.1:3306/yt_demo
  username: root
  password: 123456
  # 使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  filters: stat
  maxActive: 20
  initialSize: 1
  maxWait: 60000
  minIdle: 1
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 20


elasticsearch:
  host: 127.0.0.1
  port: 9200

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
#mybatis:
#  mapper-locations: classpath:xmlmapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.just.ytdemo.entity
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
#  endpoint:
#      health:
#        show-details: always
